apiVersion: apps/v1
kind: Deployment
metadata:
  name: walletapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: walletapp
  template:
    metadata:
      labels:
        app: walletapp
    spec:
      containers:
      - name: walletapp
        image: walletapp:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://db:5432/walletdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update